### ISSUE TITLE
Output grammar as ES module.

### ISSUE THREAD

**Issue by independentgeorge** [kach/nearley#298]
The fact that the output is UMD wrapped breaks native `import`s used inside the grammar as they are not in top-level scope.

Is adding an ES preprocessor an option?

**Comment by tjvr** [comment]
Hi! Yes, an option to output as a module makes sense to me.

Unfortunately, I don’t think Node supports modules yet—which would make this hard to test!

Would you like to send a PR? The relevant code is in `generate.js`, and the relevant tests are in `nearleyc.test.js`. :)

**Comment by independentgeorge** [comment]
Sure thing, I'll gladly do it!

Is naming the preprocessors `es` and `ecmascript` ok? It might be confused with the default `javascript`.
