### ISSUE TITLE
Internal vs external tokenizers

### ISSUE THREAD

**Issue by akonsu** [kach/nearley#315]
From https://nearley.js.org/docs/tokenizers:

> `reset(chunk, info)` sets the internal buffer of the lexer to `chunk`,
> and restores its state to a state returned by `save()`
> 

1. What is "internal buffer of the lexer"?
2. What is `chunk`?

**Comment by tjvr** [comment]
Do the [moo docs](https://github.com/no-context/moo/blob/master/README.md) help clarify at all?

`chunk` is a string. When you call feed(), Nearley uses reset() to feed the string to the lexer; it then calls next() to parse each token, until it reaches the end of the chunk. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akonsu** [comment]
Oh, I see, I need to give the input string to the parser and the parser creates an instance of the lexer and gives the string to the lexer...

Can I attach an existing instance of my lexer to the parser?

In my case I have no input string, I have a list of tokens that my lexer is ready to supply when `next()` is called. I, of course, have an input string somewhere in my code, this is where the tokens are coming from, but I would like to avoid passing the string to the parser, I just want to give the parser a lexer that would emit tokens.

To me this setup actually makes more sense: it is like a pipe in unix shell: I give a string to lexer, and the lexer pipes the tokens to the parser. Why would parser care about anything else?

I suppose I can just pass an empty string to the parser to go around this...

**Comment by tjvr** [comment]
Oh, in that case just give an array to feed() instead of a string. No need to mess with our Lexer interface at all :-) This is definitely documented, but things got a little bit confused when we added built-in Lexers. feed() has always accepted either strings or arrays.

The built-in Lexer interface is more tightly-coupled than you expected, in order for things like error formatting to work, as well as to support esoteric features such as rewinding.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tjvr** [comment]
It is documented, [here](https://nearley.js.org/docs/tokenizers#custom-token-matchers)—it’s just hard to find. We’re still working out how to explain and contrast these two approaches, while making clear we recommend moo for most uses (although using any tokeniser at all tends to be better than none)! :)

Creating a new parser instance is recommended, yes. Creating a parser is very cheap; the up-front work happens in the Grammar constructor (and nearleyc!), so just make sure to re-use the Grammar instance.

If you’re interested, we welcome pull requests to improve the docs; sounds like you understand Nearley a lot better now :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akonsu** [comment]
Yes, I was thinking that I should make a pull request describing what I gathered from this..

The reference to token matchers says that I can feed an array of objects instead of a string, but it does not explain what objects these are... And the example there feeds an array of strings. I still do not understand how to feed it an array of tokens... Can `feed()` take an array of tokens?

**Comment by tjvr** [comment]
Yes, you should be able to give it an array of objects. :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akonsu** [comment]
Thanks for all your help. Sorry, but I have one more related problem:

My grammar:
```
expr -> %SYMBOL %OPENBRACKET "{" %SYMBOL "=" %INT "}" "," expr %CLOSEBRACKET
      | %SYMBOL "+" expr
      | %SYMBOL
```
When I compile it, it creates things like
```
...
ParserRules: [
    {"name": "expr", "symbols": [SYMBOL, OPENBRACKET, {"literal":"{"}, SYMBOL, {"literal":"="}, INT, {"literal":"}"}, {"literal":","}, "expr", CLOSEBRACKET]},
    {"name": "expr", "symbols": [SYMBOL, {"literal":"+"}, "expr"]},
    {"name": "expr", "symbols": [SYMBOL], "postprocess": id}
]
...
```
The documentation says
> Use `%token` to match a token with type `token`
Which I read as that I need to do
`parser.feed([{type: 'SYMBOL', value: 'foo'}, {type: 'OPENBRACKET', ...}, ...])`
Apparently, this is not what it needs...
Please help.

**Comment by tjvr** [comment]
Ah, yes. You have to use custom marchers; see <https://nearley.js.org/docs/tokenizers#custom-token-matchers>.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akonsu** [comment]
In other words, to feed the parser a list of token objects, not a string, or a list of strings, but a list of tokens, I need to use custom matchers. Even "`{literal: '...'}` won't work, only `{test: ...}`. Is this correct?

**Comment by tjvr** [comment]
You can use `{literal}` or `{test}` for your matchers, and you refer to matchers by `%` plus their name. (The docs section is correct here.) You can also use `{type}`, I think (that part isn’t documented, since it was a more recent addition.)

You _can’t_ use literal strings such as `”foo”` in your nearley grammar; you have to define matchers for them, eg

  const foo = {literal: “foo”}
  %}
  thing -> %foo

Does that make sense? Let me know how you get on! Again, sorry this has been so confusing :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akonsu** [comment]
> You can’t use literal strings such as "foo" in your nearley grammar; you have to define matchers for them, eg

const foo = {literal: "foo"}
%}
thing -> %foo

I think you can use strings in grammars because the nearleyc compiler converts them to `{literal}` automatically..

**Comment by tjvr** [comment]
> I think you can use strings in grammars because the nearleyc compiler converts them to `{literal}` automatically..

No; without the `@lexer` option (which is only for _internal_, built-in tokenizers), Nearley separates string literals out into characters: `"foo"` becomes `[{literal: "f"}, {literal: "o"}, {literal: "o"}]`.

**Comment by tjvr** [comment]
_(Aside: I edited your comment by mistake, instead of replying to it! Sorry about that.)_
