### ISSUE TITLE
Use `ne` everywhere

### ISSUE THREAD

**Issue by tjvr** [kach/nearley#317]
Now that GitHub [highlights `.ne` files](https://github.com/github/linguist/pull/3781), it would be nice to highlight the code examples in the docs too.

Unfortunately, the syntax highlighter we use on the docs (highlight-js) isn't compatible with the highlighter GitHub uses (linguist). So there are two things to do:

1. Use `ne` triple-backtick code blocks everywhere there's a code example in the docs (found in `docs/md/`):

        ```ne
        foo -> bar
        ```

2. Highlight `js` and `ne` correctly in the docs (covered by existing issue #282).

If anyone wants to contribute a PR for (1), it would be most welcome :-)

**Comment by coolreader18** [comment]
I could do this when I get home, maybe an hour or so

**Comment by kach** [comment]
As far as I can tell, this broke syntax highlighting on the website. :-/
