### ISSUE TITLE
Convert (E)BNF (W3C)?

### ISSUE THREAD

**Issue by strarsis** [kach/nearley#328]
@timfel: Is there a tool or way for converting existing (E)BNF (W3C) grammar to nearley grammar?
E.g. from https://www.w3.org/TR/SVG/animate.html#TimingAttributes ?

nearley can also stringify an AST back to a string, right?

**Comment by Hardmath123** [comment]
There isn't a standard for EBNF grammars, afaik, but you should be able to convert the W3C grammars to nearley grammars with some simple string processing.

You can walk the AST created by nearley to stringify it. I think @tjvr might have been working on an automated tool for this at some point…?

**Comment by tjvr** [comment]
I wrote `nearley-reverse` for converting ASTs back into strings: but it’s only really necessary if you care about omitting parentheses/operator precedence, and it requires extra annotations on your postprocessors

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by strarsis** [comment]
@tjvr, @Hardmath123: There is a config tool that allows bijectional translation, http://augeas.net/.
