### ISSUE TITLE
Is there a public API to generate strings from a compiled grammar?

### ISSUE THREAD

**Issue by cemulate** [kach/nearley#334]
I would like to generate strings from a compiled grammar `.js` file in the browser -- i.e., exactly what `nearley-unparse` does. However, I can't figure out from the documentation how to accomplish this. The functionality appears to be entirely contained in `nearley-unparse.js`, but said file is not any sort of `import`able module.

It seems to me like the generation functions should be part of a core library that could then be imported in `nearley-unparse.js` or any other arbitrary place in user code. 

Am I missing something?

**Comment by tjvr** [comment]
Closing, since the patch was merged! 🎉
