### ISSUE TITLE
Typescript 2.6 strictFunctionTypes issue

### ISSUE THREAD

**Issue by maxencefrenette** [kach/nearley#337]
When and only when strictFunctionType is on, I get the following issue:

![image](https://user-images.githubusercontent.com/431838/35259032-4c82a332-ffd1-11e7-9607-a0a274825bd0.png)

Here are the packages versions I use. I believe this issue will happen with any Nearley + Moo setup with Typescript 2.6+ in strict mode.

```
"moo": "^0.4.3",
"nearley": "^2.11.0",
"typescript": "^2.6.2"
"@types/nearley": "^2.11.0",
"@types/node": "^9.3.0",
```

**Comment by tjvr** [comment]
I’m afraid we (the maintainers) don’t provide TypeScript support! 😕 The TS bindings are maintained by third parties.

You might try asking at `@types/nearley` or `@types/moo`? 🙂

**Comment by tjvr** [comment]
Closing, since it's been a while.
