### ISSUE TITLE
Predicting tokens / Showing suggestions / Implementing autocomplete

### ISSUE THREAD

**Issue by inad9300** [kach/nearley#342]
On nearley's home page it says

> nearley is built on an idiomatic streaming API. You even have access to partial parses to build predictive user interfaces.

Is there any documentation or examples on how to do something like that? I cannot find how to access partial parses in order to give suggestions for the next/current token.

Thanks!

**Comment by tjvr** [comment]
There's nothing supported yet, but it's possible in theory -- <http://tosh.tjvr.org/> uses an autocomplete mechanism based on an Earley parser.

This is a pretty difficult problem, and I'm afraid you're on your own :)

Previously: #324, #316

**Comment by inad9300** [comment]
Thanks for your quick response.

If there is no way to access partial parses, please remove that from the list of features.
