### ISSUE TITLE
Unexpected token with moo lexer

### ISSUE THREAD

**Issue by inad9300** [kach/nearley#344]
I would like to use the moo lexer together with nearley, but I keep getting the error `Unexpected column token` for various reasons for very simple strings, such as `"description contains abc"`.

I'm trying to implement some kind of searching language where you can do things like `username = xyz and ("full name" contains " A. " or "full name" contains " B. ")`.

Before moving to the moo lexer everything was working kind of nicely. Perhaps by having a look at the grammar someone knows what I am doing wrong? That would really help me :)

```
@preprocessor typescript

@{%
const moo = require('moo');

const lexer = moo.compile({
    ws: {match: /\s+/, lineBreaks: true},
    connector: /and|or/, // Any difference with `connector: ['and', 'or']`?
    leftParen: '(',
    rightParen: ')',
    field: /(?:[A-Za-z][A-Za-z0-9_]*)|(?:"[A-Za-z][A-Za-z0-9_ ]*?")/,
    operator: /contains|not contains|=|<|>/,
    value: /(?:[^\s()"]+)|(?:"[^\s()"]*?")/
});
%}

@lexer lexer

bexp -> bexp %ws %connector %ws bexp
bexp -> %leftParen _ bexp _ %rightParen
bexp -> pred

pred -> %field %ws %operator %ws %value
```

**Comment by tjvr** [comment]
Hey! I can’t provide more detailed help right now, but the tl;dr is that it looks like you’re trying to do too much in your lexer.

You’ll also find that `contains` is lexed as a `field`, because field has higher priority :)

I would look into moo’s keyword feature, and make sure to split up `not contains` into two separate tokens :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by inad9300** [comment]
Thanks for your response. I figured out the problem with the priority. I have redefined my syntax like this: 

```ts
const lexer = moo.compile({
    ws: {match: /\s+/, lineBreaks: true},
    leftParen: '(',
    rightParen: ')',
    operator: ['contains', 'not contains', '=', '<', '>'],
    connector: ['and', 'or'],
    term: [
        {match: /[^\s()"=<>]+/},
        {match: /".*?"/, value: stripQuotes},
    ]
});
```

The output produced by the lexer looks really good. It is able to separate everything properly now without problems. As it is, it's really convenient and I might even be able to use it to show suggestions/auto-complete.

In particular, I didn't have a problem with `not contains` being one token. Why exactly do you recommend splitting it? Also, I'm very interested in knowing why I am doing too much in the lexer; to me it looks like it contains very simple rules that you can find in any moo example.

However the parser has still some problems. For example, it is able to parse:
```
name contains abc and description = def or text not contains ghi
```
But parenthesis seem to be a problem, since it fails to parse:
```
name contains abc and (description = def or text not contains ghi)
```
With the message:
```
  name like abc and (description
                     ^
Unexpected term token: "description"
```

**Comment by tjvr** [comment]
Regarding `not contains`: I’m not entirely sure, it just seems unusual to me. For one thing, you’ll have to copy your white space rule, or you’ll lex `not     contains` wrong :)

Your lexer looks much better to me now!

Regarding your last issue, I think it’s a problem with your grammar? :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tjvr** [comment]
Ah, I think you need to make sure whitespace is optional. Perhaps define `_ -> %ws:?`, and use in your grammar, between all the words.

I should also point out that your first grammar rule is ambiguous, since it has the form `X -> X ... X`; you need to introduce a separate grammar rule to avoid this, so you can control precedence: eg `X -> X ... Y` for left-associative.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by inad9300** [comment]
What do you mean by "copy your white space rule"?

About the problem with the white space, notice that I am already using the built-in `_` inside the parenthesis. And around the connectors and operators I enforce at least one white space. So I'm not sure where else to permit them nor why.

And finally about the ambiguity, how would I define `Y`? Just as `Y -> X`? I don see it 😕

Thanks a ton for all the help!

**Comment by tjvr** [comment]
> Thanks a ton for all the help!

You're welcome! Unlike some issues, this has been a very pleasant interaction 😃 

> copy your white space rule

Only that you'll need to write `/not\s+contains/` to be consistent with how whitespace between other words is handled :) It's definitely up to you whether to separate `not contains` into two tokens or not, I don't think it matters!

> I enforce at least one white space

Hmm, good point! If you want to disallow `foo=bar` (with no spaces!), then that's the way to go. I'm not sure if the built-in `_` will work with Moo, though.

---

I think I'd do something like this:

```js
const lexer = moo.compile({
    ws: {match: /\s+/, lineBreaks: true},
    leftParen: '(',
    rightParen: ')',
    equal: ['=', '<', '>'],
    term: [
        {match: /[^\s()"=<>]+/, keywords: {
          contains: 'contains',
          not: 'not',
          connector: ['and', 'or'],
        }},
        {match: /".*?"/, value: stripQuotes},
    ],
});
```

```ne
B -> B %ws %connector %ws C
   | C

C -> %leftParen %ws:? B %ws:? %rightParen
C -> P

P -> %field %ws Op %ws %value

Op -> %not %ws %contains
    | %contains
```

I'm afraid I'd have a hard time explaining _why_ you need separate `B` and `C` rules... [the docs](https://nearley.js.org/docs/how-to-grammar-good#operator-precedence-is-not-black-magic) might help with that. 

Let me know if anything's still unclear! 🙂

**Comment by inad9300** [comment]
You're right, I should probably allow no spaces around `=` and more than one space for `not contains`.

In your solution:
1. `equal` is not used in the grammar, I guess it would need to be part of the `Op` rule.
2. `field` and `value` are not in the lexer, I guess they both should be `term`.
3. How does `keywords` behave exactly? I ask because I would like to allow constructs such as `description contains contains` or `description contains not`, and I'm worried that this might not work with `keywords` (if I understand it correctly, you would be forced to type `description contains "contains"`, which is not that bad, but not ideal).

A more general question that I could not find in the docs: when using the `|` operator, if I want to process all the cases in the same way, is it enough with specifying one post-process function at the end?

**Comment by inad9300** [comment]
An update on my grammar with some of your suggestions :)
```ts
const lexer = moo.compile({
    ws: {match: /\s+/, lineBreaks: true},
    leftParen: '(',
    rightParen: ')',
    connector: ['and', 'or', 'AND', 'OR'],
    signOperator: ['=', '<', '>'],
    wordOperator: /contains|CONTAINS|not\s+contains|NOT\s+CONTAINS/,
    term: [
        {match: /[^\s()"=<>]+/},
        {match: /".*?"/, value: stripQuotes},
    ]
});

lexpr -> lexpr %ws %connector %ws rexpr
       | rexpr

rexpr -> %leftParen %ws:? lexpr %ws:? %rightParen
rexpr -> pred

pred -> col %ws:? %signOperator %ws:? val
pred -> col %ws %wordOperator %ws val

col -> %term
val -> %term
```

After feeding the parser with `name contains abc` I still get:

```
  name
  ^
Unexpected term token: "name"
```

**Comment by tjvr** [comment]
Apologies for the mistakes above; sounds like you've spotted them correctly! 🙂

> how to achieve case-insensitivity for keywords?

Sounds like I should merge https://github.com/no-context/moo/pull/78 :-)

> if I want to process all the cases in the same way, is it enough with specifying one post-process function at the end?

No, sorry: you'll need one postprocessor for each case. (Or you can use grouping! https://github.com/kach/nearley/issues/332#issuecomment-354593418)

> if I understand it correctly, you would be forced to type `description contains "contains"`

That's correct :) Keywords are described here: https://github.com/no-context/moo#keywords

Your case is actually an interesting problem. Normally, you don't want to be able to use keywords as identifiers. You could omit keywords from your lexer, and use `"contains"` instead of `%contains` in your grammar. But the grammar rule would then match any token with that _value_, and so you'd also accept `foo "contains" bar`!

**Comment by inad9300** [comment]
It's not a big deal to actually have keywords and forbid them as values. I'm more concern about just making it work! 😅

**Comment by inad9300** [comment]
I've just seen your edition. I still don't see why the example I posted (`name contains abc`) is giving problems. `name` is correctly identified as a term, and terms are allowed to be at the beginning of predicates and therefore also at the beginning of expressions.

Grouping is very useful, thanks for the hint. (What about including it in the docs? 🙃)

I have tried to use keywords as you suggested, separating `not` and `contains` and so on. Unfortunately, the following exception is risen: `ReferenceError: connector is not defined`. It seems that I am not able to refer to keywords in the grammar using the notation `%connector`. How do I achieve that?

Here is again the latest version of my grammar:
```ts
const lexer = moo.compile({
    ws: {match: /\s+/, lineBreaks: true},
    leftParen: '(',
    rightParen: ')',
    signOperator: ['=', '<', '>'],
    term: [
        {
            match: /[^\s()"=<>]+/,
            keywords: {
                not: 'not',
                contains: 'contains',
                connector: ['and', 'or']
            }
        },
        {match: /".*?"/, value: stripQuotes},
    ]
});
```
```ne
lexpr -> lexpr %ws %connector %ws rexpr
       | rexpr

rexpr -> %leftParen %ws:? lexpr %ws:? %rightParen
rexpr -> pred

pred -> col %ws:? %signOperator %ws:? val
pred -> col %ws wordOperator %ws val

col -> %term
val -> %term

wordOperator -> %not %ws %contains
              | %contains
```

**Comment by tjvr** [comment]
Your latest grammar looks a lot better to me :)

I found a computer and tried your last two examples, and I'm afraid they both work fine for me 🤔 While I think we've solved some problems you might have down the road, perhaps I've been chasing the wrong problem!

Please can you post your full `.ne` file, the versions of `moo` and `nearley` you're using, and the steps you're using to test? :)

**Comment by inad9300** [comment]
Absolutely. Whatever helps you to help me, I'll do :)

I'm using version 2.11.0 of nearley and version 0.4.1 of moo. I'm running the code in [RunKit](https://runkit.com/home). Here is the whole content of my `.ne` file (notice the switch from `contains` to `like`):

```ne
@preprocessor typescript

@{%
const moo = require('moo');

const stripQuotes = (str: string): string => {
    return str[0] === '"' && str[str.length - 1] === '"'
        ? str.substring(1, str.length - 1)
        : str;
};

const connectors = {
    'and': 'AND',
    'or': 'OR'
};

const operators = {
    'like': 'LIKE',
    'not like': 'NOT_LIKE',
    '=': 'EQ',
    '<': 'LT',
    '>': 'GT'
};

const lexer = moo.compile({
    space: {match: /\s+/, lineBreaks: true},
    leftParen: '(',
    rightParen: ')',
    signOperator: ['=', '<', '>'],
    term: [
        {
            match: /[^\s()"=<>]+/,
            keywords: {
                not: 'not',
                like: 'like',
                connector: ['and', 'or']
            }
        },
        {match: /".*?"/, value: stripQuotes},
    ]
});

const removeSpaces = (d: any[]) => d.filter((token) => token && token.type !== 'space');

const buildExprPairNode = (d: any[]) => ({
    type: connectors[d[1].value],
    leftChild: d[0],
    rightChild: d[2]
});

const buildExprWithParensNode = (d: any[]) => ({
    type: 'PARENS',
    leftChild: d[1]
});

const buildPredNode = (d: any[]) => ({
    type: operators[d[1].value],
    data: {column: d[0].value, value: d[2].value}
});
%}

@lexer lexer

lexpr -> lexpr %space %connector %space rexpr  {% d => buildExprPairNode(removeSpaces(d)) %}
       | rexpr                                 {% id %}

rexpr -> %leftParen %space:? lexpr %space:? %rightParen  {% d => buildExprWithParensNode(removeSpaces(d)) %}
rexpr -> pred                                            {% id %}

pred -> col %space:? %signOperator %space:? val  {% d => buildPredNode(removeSpaces(d)) %}
pred -> col %space wordOperator %space val       {% d => buildPredNode(removeSpaces(d)) %}

col -> %term  {% id %}
val -> %term  {% id %}

wordOperator -> %not %space %like  {% () => ({value: 'not like'}) %}
              | %like              {% id %}
```

Now, to test it I run `nearleyc`, copy the output into [TypeScript's playground](https://www.typescriptlang.org/play/), tweak it a bit (remove the `export`s and wrap `Lexer`, `ParserRules` and `ParserStart` in a `grammar` object), and copy the result into RunKit.

There I run the following code:
```js
const nearley = require("nearley");
const moo = require("moo");

/************************************************************************************************************/
// Generated automatically by nearley
// http://github.com/Hardmath123/nearley
function id(d) { return d[0]; }
var stripQuotes = function (str) {
    return str[0] === '"' && str[str.length - 1] === '"'
        ? str.substring(1, str.length - 1)
        : str;
};
var connectors = {
    'and': 'AND',
    'or': 'OR'
};
var operators = {
    'like': 'LIKE',
    'not like': 'NOT_LIKE',
    '=': 'EQ',
    '<': 'LT',
    '>': 'GT'
};
var lexer = moo.compile({
    space: { match: /\s+/, lineBreaks: true },
    leftParen: '(',
    rightParen: ')',
    signOperator: ['=', '<', '>'],
    term: [
        {
            match: /[^\s()"=<>]+/,
            keywords: {
                not: 'not',
                like: 'like',
                connector: ['and', 'or']
            }
        },
        { match: /".*?"/, value: stripQuotes },
    ]
});
var removeSpaces = function (d) { return d.filter(function (token) { return token && token.type !== 'space'; }); };
var buildExprPairNode = function (d) { return ({
    type: connectors[d[1].value],
    leftChild: d[0],
    rightChild: d[2]
}); };
var buildExprWithParensNode = function (d) { return ({
    type: 'PARENS',
    leftChild: d[1]
}); };
var buildPredNode = function (d) { return ({
    type: operators[d[1].value],
    data: { column: d[0].value, value: d[2].value }
}); };
var grammar = {
    Lexer: lexer,
    ParserRules: [
        { "name": "lexpr", "symbols": ["lexpr", (lexer.has("space") ? { type: "space" } : space), (lexer.has("connector") ? { type: "connector" } : connector), (lexer.has("space") ? { type: "space" } : space), "rexpr"], "postprocess": function (d) { return buildExprPairNode(removeSpaces(d)); } },
        { "name": "lexpr", "symbols": ["rexpr"], "postprocess": id },
        { "name": "rexpr$ebnf$1", "symbols": [(lexer.has("space") ? { type: "space" } : space)], "postprocess": id },
        { "name": "rexpr$ebnf$1", "symbols": [], "postprocess": function () { return null; } },
        { "name": "rexpr$ebnf$2", "symbols": [(lexer.has("space") ? { type: "space" } : space)], "postprocess": id },
        { "name": "rexpr$ebnf$2", "symbols": [], "postprocess": function () { return null; } },
        { "name": "rexpr", "symbols": [(lexer.has("leftParen") ? { type: "leftParen" } : leftParen), "rexpr$ebnf$1", "lexpr", "rexpr$ebnf$2", (lexer.has("rightParen") ? { type: "rightParen" } : rightParen)], "postprocess": function (d) { return buildExprWithParensNode(removeSpaces(d)); } },
        { "name": "rexpr", "symbols": ["pred"], "postprocess": id },
        { "name": "pred$ebnf$1", "symbols": [(lexer.has("space") ? { type: "space" } : space)], "postprocess": id },
        { "name": "pred$ebnf$1", "symbols": [], "postprocess": function () { return null; } },
        { "name": "pred$ebnf$2", "symbols": [(lexer.has("space") ? { type: "space" } : space)], "postprocess": id },
        { "name": "pred$ebnf$2", "symbols": [], "postprocess": function () { return null; } },
        { "name": "pred", "symbols": ["col", "pred$ebnf$1", (lexer.has("signOperator") ? { type: "signOperator" } : signOperator), "pred$ebnf$2", "val"], "postprocess": function (d) { return buildPredNode(removeSpaces(d)); } },
        { "name": "pred", "symbols": ["col", (lexer.has("space") ? { type: "space" } : space), "wordOperator", (lexer.has("space") ? { type: "space" } : space), "val"], "postprocess": function (d) { return buildPredNode(removeSpaces(d)); } },
        { "name": "col", "symbols": [(lexer.has("term") ? { type: "term" } : term)], "postprocess": id },
        { "name": "val", "symbols": [(lexer.has("term") ? { type: "term" } : term)], "postprocess": id },
        { "name": "wordOperator", "symbols": [(lexer.has("not") ? { type: "not" } : not), (lexer.has("space") ? { type: "space" } : ws), (lexer.has("like") ? { type: "like" } : like)], "postprocess": function (d) { return ({value: 'not like'}); } },
        { "name": "wordOperator", "symbols": [(lexer.has("like") ? { type: "like" } : like)], "postprocess": id }
    ],
    ParserStart: "lexpr",
};
/************************************************************************************************************/

//              0123456789 11 14 17 20
const query = 'name not like abc';

lexer.reset(query);
console.log('tokens', Array.from(lexer));

const compiledGrammar = nearley.Grammar.fromCompiled(grammar);
const parser = new nearley.Parser(compiledGrammar);
parser.feed(query);
console.log('parser', parser);
```

For the moment I patched it by adding new entries to the lexer at the top level, which are a copy of the keywords, i.e.
```js
moo.compile({
    // ...
    not: 'not',
    like: 'like',
    connector: ['and', 'or'],
    term: [
        {
            match: /[^\s()"=<>]+/,
            keywords: {
                not: 'not',
                like: 'like',
                connector: ['and', 'or']
            }
        },
        { match: /".*?"/, value: stripQuotes },
    ]
});
```

**Comment by tjvr** [comment]
Can you try using Moo 0.4.3 please? :) I think we fixed a bug with `keywords` recently.

If that still doesn't work, I'll take a look.

**Comment by inad9300** [comment]
No need to look into the code, it is working with 0.4.3 without problems.

Thanks a lot for all your help!

**Comment by tjvr** [comment]
Hooray! 🎉

I'm glad we got it sorted 😄

I agree there are a few things we could improve in the documentation; feel free to raise issues or PR these if you have time :-)
