### ISSUE TITLE
randexp dependency

### ISSUE THREAD

**Issue by fedebertolini** [kach/nearley#346]
Hi there :)
Yesterday version [0.4.7](https://github.com/fent/randexp.js/releases/tag/v0.4.7) of `randexp` was published, which contains a breaking change when running `npm install` in a git-less environment.
There's already an [issue](https://github.com/fent/randexp.js/issues/46) created in their repository, but maybe in the meantime you could lock the dependency to version `0.4.6`?
Thanks!

**Comment by tjvr** [comment]
I’d be happy to do that :-) If you can send a quick PR, I’ll merge it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fedebertolini** [comment]
@tjvr done :) https://github.com/kach/nearley/pull/347
