### ISSUE TITLE
Build error with a comment just before the end of a grammar file

### ISSUE THREAD

**Issue by MartinKavik** [kach/nearley#349]
Hi guys!
I'm afraid I've found a bug.

Last lines in **grammar.ne**:
```
...
_ -> %__:?     {% nuller %}
# --- //terminals ---
```

**Build error** (I'm using [nearley-template](https://github.com/appology/nearley-template) btw):
```
[build] C:\new_projects\extensions\elm-ast\node_modules\nearley\lib\compile.js:25
        for (var i = 0; i < structure.length; i++) {
                                      ^

TypeError: Cannot read property 'length' of undefined
    at Compile (C:\new_projects\extensions\elm-ast\node_modules\nearley\lib\compile.js:25:39)
    at StreamWrapper.<anonymous> (C:\new_projects\extensions\elm-ast\node_modules\nearley\bin\nearleyc.js:57:17)
    at emitNone (events.js:110:20)
    at StreamWrapper.emit (events.js:207:7)
    at finishMaybe (_stream_writable.js:604:14)
    at endWritable (_stream_writable.js:612:3)
    at StreamWrapper.Writable.end (_stream_writable.js:563:5)
    at ReadStream.onend (_stream_readable.js:595:10)
    at Object.onceWrapper (events.js:312:30)
    at emitNone (events.js:110:20)
[build] [nodemon] app crashed - waiting for file changes before starting...
```

When I delete that last comment from grammar.ne, everything works. 

My SW:
- `node -v` => v8.8.1
- `npm -v` => 5.6.0
- `nearleyc -v` => 2.11.1
- Windows 10

---

Very nice project, I've just found it today and I am trying to write parser for Elm, thanks :)

**Comment by tjvr** [comment]
Hey, thanks for reporting!

I doubt we'll get to this soon; is it blocking you?  🙂

**Comment by MartinKavik** [comment]
@tjvr No, it's low prio. You can leave it to me, I'll try to send PR, thanks  :)

**Comment by kach** [comment]
Is your file newline-terminated? If so, this is #128 and we consider this expected behavior.

**Comment by MartinKavik** [comment]
Yeah, it is the same issue, I haven't read closed issues before posting this one.

`Cannot read property 'length' of undefined` is very confusing way to say _"You have to add new line because of ...."
Btw why is necessary to add new line, pls? Thanks!

**Comment by kach** [comment]
\n is how you tell nearley that you are done with the comment. In any case, I think all files _should_ be \n-terminated. If you `cat` a non-newline-terminated file, it messes up your prompt! (You can configure your editor to do \n-terminate if it doesn't already.)
