### ISSUE TITLE
Best way to find out which rule was violated?

### ISSUE THREAD

**Issue by newtang** [kach/nearley#356]
Hi, I looked through the questions and I didn't see this asked.

What's the best way to identify which rule is being violated? For instance, if I had a date parser, and I insisted on a 2 digit year, and the input is '3/5/2018', how can I know that it was "year" that was violated. Here's a quick grammar example.

```
expression -> date 
date -> monthday "/" monthday "/" year 
year -> digit digit 
monthday -> 
    digit  
  | digit digit 
```

You could imagine I have a date-time rule which references the above date rule and some other rule, for example.

**Comment by tjvr** [comment]
Hey! Thanks for looking through the questions before asking :)

I'm afraid I'm not sure how to help with this. With parsers and context-free-grammars in general, there's not really a concept of which rule was "violated".

I suppose you're wanting better error messages from your parser? There's no nice way of doing this at the moment, I'm afraid. Although I should note that the default error messages are often a little clearer if you're using a [tokenizer](https://nearley.js.org/docs/tokenizers).

Sorry I can't be more helpful!

**Comment by newtang** [comment]
Ah, I see what you mean. Thanks for the tip!
