### ISSUE TITLE
Unexpected multiple parser results. 

### ISSUE THREAD

**Issue by fstiffo** [kach/nearley#363]
I wrote this simple grammar:

[https://gist.github.com/fstiffo/3a6c9b105c1a9a56e14a384831b16a14]()

then I tested it with this simple text:

`nearley-test  -i "[short_abstr(['1%%A']),'type%%retor_polits',extabst(['1%%A'])]" -o parsed.txt sommas.js`

Here the result:

[https://gist.github.com/fstiffo/705debefe5b59cf71286f4de120aac13]()

There are 15 parses too much.

The grammar is not ambiguos, the parse chart proves it. 

Any idea?

Thx in advance.

**Comment by tjvr** [comment]
I'm afraid that if there are multiple results, then it means your grammar is ambiguous!

Fortunately, I can spot at least one problem quite easily: you've written the `SENTENCES` rule twice 🙂 Duplicating a rule like this will result in ambiguity.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fstiffo** [comment]
Yes of course, thanks a lot!! I did not see the duplication because originally the project is composed by I many files one for each main rule. I put all together only for the gists file. Sorry for bothering you.

**Comment by tjvr** [comment]
No problem! Glad you solved it 😊
