### ISSUE TITLE
Dependency `nomnom ~1.6.2` is unmaintained

### ISSUE THREAD

**Issue by bjacobel** [kach/nearley#364]
Installing nearley (or packages with dependencies on it) results in this error in Yarn:

```
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
```

`nomnom`'s former maintainer recommends migrating to commander.js.

**Comment by tjvr** [comment]
Thanks; this has been reported already :)

**Comment by kach** [comment]
Yes, we should do something about that. Ugh.

**Comment by apaatsio** [comment]
Currently, I can't find any open issues about this nomnom deprecation. Maybe we should create a new issue for tracking the "Switch from nomnom to commander".

I'm sure there are many people searching this repo for *open* issues about nomnom.
