### ISSUE TITLE
Sharing a tokenizer among included grammars

### ISSUE THREAD

**Issue by wgerven** [kach/nearley#368]
Hi,

I am writing a grammar which is separated into several files. I have an `index.ne` file which `@include`s all child grammars. I use moo as a tokenizer. My problem/question is as follows:

I need to import my lexer object into every child file, but I don't have to include it into the `index.ne` file, even if `index.ne` references tokens in the lexer. 

However, in every child ne file, I am obliged to set the lexer to a distinct variable name, because otherwise I get naming clashes. 

If I only include in the `index.ne` file, variables in the ParserRules will not be defined. 

For instance, the only way in which I can share a lexer object amongst several files of the same grammar is as follows:

lexer.js
```
const { compile } = require('moo'); 

module.exports = compile({
    question: 'is it rainy?',
    answer: 'no',
    repeat: 'what?'
})
```

index.ne
```
@include "./question.ne"
@include "./answer.ne"

interview -> question | answer | %repeat
```
notice I reference a token of the lexer, but didn't have to include it.

question.ne
```
@{%
const lex1 = require('./lexer');
%}
@lexer lex1

question -> %question
```

answer.ne
```
@{%
const lex2 = require('./lexer');
%}
@lexer lex2

answer -> %answer
```

compiled parser.js:
```
(function () {
function id(x) { return x[0]; }

const lex2 = require('./lexer');


const lex1 = require('./lexer');
var grammar = {
    Lexer: lex1,
    ParserRules: [
    {"name": "question", "symbols": [(lex2.has("question") ? {type: "question"} : question)]},
    {"name": "answer", "symbols": [(lex1.has("answer") ? {type: "answer"} : answer)]},
    {"name": "interview", "symbols": ["question"]},
    {"name": "interview", "symbols": ["answer"]},
    {"name": "interview", "symbols": [(lex1.has("repeat") ? {type: "repeat"} : repeat)]}
]
  , ParserStart: "interview"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
```
note `lexer.js` is required twice, and that the rule from `index.ne` uses a lexer defined in one of the child grammars. This appears to be the *only* way in which I can share a lexer among several parts of a grammar. 

Is this correct? And also, is this obvious? Because to me it wasn't. I only found it out after trial and error. Wouldn't it be more natural to be able to specify a single lexer in `index.ne`, shared with all child grammars?

Thanks for making Nearley!

Willem.

**Comment by coolreader18** [comment]
You don't have to redefine the lexer for each included .ne file, you can just do
```ne
@{%
  const lex = require("./lexer");
%}
@lexer lex
```
another file:
```ne
@lexer lex
thing -> %token
```

**Comment by wgerven** [comment]
Ah ok! Thanks, somehow an obvious thing to try, but it didn't occur to me.
