### ISSUE TITLE
How to stop "parser.feed(...)"?

### ISSUE THREAD

**Issue by guigaoliveira** [kach/nearley#375]
In my web application, I need to do the parser of the grammar using a textArea, when I update the textArea I want to do the grammar parser, so I use the parser.feed (...). How do I clear the parser.feed (...)?

**Comment by Morpheu5** [comment]
I have the same problem. A non-solution is to recreate the parser every time, which is what I'm doing. An alternative solution is to use `reset()`, but I haven't tried, so I may be completely off-track here.

**Comment by tjvr** [comment]
The recommended way _is_ to re-create the parser every time; creating the `Parser` is cheap. (Creating a `Grammar`, e.g. using `fromCompiled`, is more expensive; you should not re-create the Grammar each time. :-))

**Comment by guigaoliveira** [comment]
Thank you for the clarification @tjvr.
