### ISSUE TITLE
Two non-terminals parsed one after the other result in weird non-ambiguous parsing

### ISSUE THREAD

**Issue by Morpheu5** [kach/nearley#379]
Please see [this SO question](https://stackoverflow.com/questions/50482742/nearley-grammar-matches-the-same-bit-of-text-as-a-terminal-and-a-non-terminal-on) and [this grammar](https://gist.github.com/Morpheu5/915feecf45dba50280570a60831a517f).

In short, I have a non-terminal to match alphabetic strings (`SY`, in that grammar) which then should get trumped by another non-terminal (`FN`) to recognise functions. It appears that in some cases (see SO question) `sin(x)` gets recognised both as a `SY => "sin"` and as a `FN => "sin(x)"`, in this order. I suspect the `processMultiplication` function is adding to the chaos.

I'm almost completely a noob when it comes to grammars, so I'm not even sure where to start from when debugging this. Any clues?

**Comment by matthew-dean** [comment]
@Morpheu5 I think your question may be similar to my question here: https://github.com/kach/nearley/issues/382

In other words, you can't have a token match of a specific string "sin" and also a match to any alpha-numeric sequence. Nearley won't "choose" one; it will choose both. `Rule -> "sin" | [a-z]:+` will both match to "sin", for example, so it's ambiguous. Instead you have to write (I think), just the alpha-numeric match, and then in your post-processor, filter by specific names to do other actions.

**Comment by Morpheu5** [comment]
Hey @matthew-dean, sorry I forgot to update this. That was my first solution, but it seems that the proper way is to use keywords, as explained [here](https://github.com/no-context/moo/blob/master/README.md#keywords).

**Comment by matthew-dean** [comment]
@Morpheu5 Ah. I haven't used moo so I wouldn't know. I still consider myself a parsing grammar noob as well.
