### ISSUE TITLE
Preventing Nearley from having multiple matches (default match?)

### ISSUE THREAD

**Issue by matthew-dean** [kach/nearley#382]
So, every once in a while I dust off a nearley grammar file for Less to try to get it to a point where it can actually create Less nodes (with the thought that maybe some day it would replace the existing Less parser).  (If you're curious, see the WIP - https://github.com/matthew-dean/less.js/blob/experiments/parser/lib/less/parser/grammar.ne)

One of the features of the Less parser that seems to conflict with Nearley's model of parsing is that the Less parser grabs the first match. Nearley seems to use the `|` pipe to indicate multiple parsings, treats all parsings as equal, and says the results are ambiguous if more than one match.

For example, while there is complex parsing for something like a CSS pseudo selector (`like :not()`), Less special cases features like `:extend()` which the parser can match first before it ever reaches the pseudo-selector rule.

So, in Nearley, how do you define something like, "For pseudo selectors or function names, try these specific strings first and IF THEY DON'T PARSE, then move on to the general parsing rules." ?

OR is this paradigm / approach entirely wrong, and should we just parse any pseudo-selector, and in the post-processor, run a function that creates a different node based on a match? (Am I answering my own question?)

**Comment by kach** [comment]
I think you got it — parse any pseudo-selector, and then deal with the type of node in the postprocessor.

**Comment by matthew-dean** [comment]
@kach Word. Yeah, by the I got to the end of what I was writing I was like,  "🤔 I think I'm approaching this wrong." lol 

Seems more efficient to just parse things as things, and then treat the results specially, rather than try to parse a string to match a specific sequence, then re-parse with a generic sequence. One of the reasons I want to use Nearley for a Less parser! Thanks for your help.

**Comment by kach** [comment]
:-)
