### ISSUE TITLE
Possible enhancement: reduce string names to constants

### ISSUE THREAD

**Issue by matthew-dean** [kach/nearley#384]
I think I brought this up when I was experimenting with Nearley years ago, but instead of producing output like this:
```js
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "Element", "symbols": ["Class"], "postprocess": id},
    {"name": "Element", "symbols": ["Id"], "postprocess": id},
    {"name": "Element", "symbols": ["Ident"], "postprocess": id},
    {"name": "Element", "symbols": ["Attr"], "postprocess": id},
    {"name": "Element", "symbols": [{"literal":"&"}], "postprocess": id},
    {"name": "Element", "symbols": ["Pseudo"], "postprocess": id},
    {"name": "Element", "symbols": [{"literal":"*"}], "postprocess": id}
...
]}
```
...Nearley could produce output like
```js
function Rule(obj) {
  this.name = obj.n
  this.symbols = obj.s
  this.postprocess = obj.p  //etc
}
// cache names
var NAME: {
  0: "Element"
}
var grammar = {
    Lexer: undefined,
    ParserRules: [
    new Rule({n: NAME[0], s: ["Class"], p: id},
    new Rule({n: NAME[0], s: ["Id"], p: id}),
    new Rule({n: NAME[0], s: ["Ident"], p: id}),
    new Rule({n: NAME[0], s: ["Attr"], p: id}),
    new Rule({n: NAME[0], s: [{"literal":"&"}], p: id}),
    new Rule({n: NAME[0], s: ["Pseudo"], p: id}),
    new Rule({n: NAME[0], s: [{"literal":"*"}], p: id})
...
]}
```

I mean, unless you think object lookups are more expensive that string creation, or object creation with the same prototype is more expensive than independent objects of different shapes, but it shoudn't be. At the very least, it doesn't seem like you need such verbose objects with long, human-readable string-quoted property names. It isn't that human readable anyway, so why not make concise objects with single-character (un-quoted) names?

**Comment by tjvr** [comment]
Thanks for the suggestion! I think this would be a micro-optimisation, though; JavaScript VMs are good at compiling the sort of code we have currently, and gzip compression means the longer names don't matter.

You're right they don't need to be single-quoted though!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by matthew-dean** [comment]
> Thanks for the suggestion! I think this would be a micro-optimisation, though; 

Fair enough. 👍
