### ISSUE TITLE
Nearley fails if file ends in comment

### ISSUE THREAD

**Issue by robsimmons** [kach/nearley#388]
Test file:

```
N -> "zero" | "succ(" N ")"
# Unary natural numbers
```

If the file ends in a newline, then `nearlyc test.ne` succeeds. Otherwise, it fails with an unhelpful error message:

```
C:\Home\r\jaco\node_modules\nearley\lib\compile.js:25
        for (var i = 0; i < structure.length; i++) {
                                      ^

TypeError: Cannot read property 'length' of undefined
    at Compile (C:\Home\r\jaco\node_modules\nearley\lib\compile.js:25:39)
    at StreamWrapper.<anonymous> ($PATH\nearleyc.js:57:17)
    at StreamWrapper.emit (events.js:185:15)
    at finishMaybe (_stream_writable.js:636:14)
    at endWritable (_stream_writable.js:644:3)
    at StreamWrapper.Writable.end (_stream_writable.js:586:5)
    at ReadStream.onend (_stream_readable.js:607:10)
    at Object.onceWrapper (events.js:272:13)
    at ReadStream.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
```

Expected outcome: file is accepted, or file is rejected with a more informative error message.

**Comment by kach** [comment]
Okay, okay, I give up. We'll accept trailing comments that aren't newline-delimited…

**Comment by kach** [comment]
If you upgrade to 2.15.0, it should work. :-)

**Comment by robsimmons** [comment]
I'm fine with disallowing EOF-terminated line comments! Just wasn't a good
error message. Supporting them works to of course. Thank you!

**Comment by kach** [comment]
Yeah, I'm not hugely comfortable with the way I fixed this, but I've gotten enough complaints over the past four years that it makes sense to just allow it.

P.S. Out of curiosity, what are you using nearley for? I'm always interested in how people are using it. :-)

**Comment by robsimmons** [comment]
Reimplementing a C/Java like language called C0 used for teaching imperative data structures at Carnegie Mellon. Temporary demo up at http://jaco.surge.sh , repo is https://github.com/calculemuscode/jaco

**Comment by kach** [comment]
Ooh, very cool! Thanks for the links.

Closing this issue, now.
