### ISSUE TITLE
[Help] Getting an infinite loop when using grammar recursion

### ISSUE THREAD

**Issue by v-stein** [kach/nearley#389]
Hi, I was wondering about which recursion is allowed (I have read about left recursion against right recursion but still, no luck).

What provokes the infinite loop I'm getting when entering an operation is this:

```javascript
@{%
    const Addition          = require('./classes/Addition');
    const Substraction      = require('./classes/Substraction');
    const Modulo            = require('./classes/Modulo');
    const Multiplication    = require('./classes/Multiplication');
    const Division          = require('./classes/Division');
%}

@include "./primitives.ne"
@include "./keywords.ne"
@include "./operators.ne"

main -> Operation {% id %}



Operation               ->  _ AdditionSubstraction _                            {% function (data) { return data[1]; }                  %}


AdditionSubstraction    ->  AdditionSubstraction _ Plus _ ModuloMultiplyDivide  {% function (data) { return new Addition(data); }       %}
                        |   AdditionSubstraction _ Minus _ ModuloMultiplyDivide {% function (data) { return new Substraction(data); }   %}
                        |   ModuloMultiplyDivide                                {% id %}


ModuloMultiplyDivide    ->  ModuloMultiplyDivide _ Modulo _ Parenthesized       {% function (data) { return new Modulo(data); }         %}
                        |   ModuloMultiplyDivide _ Multiply _ Parenthesized     {% function (data) { return new Multiplication(data); } %}
                        |   ModuloMultiplyDivide _ Divide _ Parenthesized       {% function (data) { return new Division(data); }       %}
                        |   Parenthesized                                       {% id %}


Parenthesized           ->  leftParenthesis _ Term _ rightParenthesis           {% function (data) { return data[2]; }                  %}
                        |   Term                                                {% id %}


Term                    ->  Primitive                                           {% id %}
                        |   Operation                                           {% id %}

```
Some notes:
 - About the classes `Addition`, `Substraction`, (...), those are just classes that extract the left and right term and the symbol used for the operation.

 - The grammar `primitives.ne` defines some grammar about primitive values, which does not include any recursion. This grammar also includes `whitespace.ne` and `symbols.ne`.

 - The grammar `whitespace.ne` defines the optional whitespace `_` and the mandatory whitespace `__`

 - The grammar `symbols.ne` just identifies symbols as `+`, `@` and assigns a new instance of a class to that token (for identification purposes).

 - The grammar `keywords.ne` identifies all keywords that aren't primitive values or identifiers (as `this`, `for`, ...)

 - The grammar `operators.ne` identifies all operators (from arithmetic to comparison and assignement ones)

And everything works fine when I write `Term` as this:

```javascript
Term                    ->  Primitive                                           {% id %}
```

So I noticed it was the `Operation` recursion in `Term` that is causing the parser to infinitely loop, but I don't see how to avoid it and get the desired result...

## Environment used:
 - Node: (io.js build) v8.10.0
 - NPM : 5.6.0
 - Nearley compiler : 2.15.0

**Comment by v-stein** [comment]
Okay, found what was the problem.

The thing is in the above problem, I was defining that a `Term` is a `Primitive` or an `Operation`.
And I was defining the `Parenthesized` as an `Operation` sourrounded by `leftParenthesis` and `rightParenthesis` or a `Term`, which an `Operation` can also be (by recursion).

What solved the problem was changing a `Term` to:
```javascript
Term -> Primitive {% id %}
```

And a `Parenthesized` to:
```javascript
Parenthesized -> leftParenthesis _ Operation _ rightParenthesis {% function (data) { return data[2]; } %}
              |  Term {% id %}
```

**Comment by kach** [comment]
Yes, I was just about to suggest doing that. Glad you figured it out.

You can look at this example for help in the future: https://github.com/kach/nearley/blob/master/examples/calculator/arithmetic.ne

**Comment by v-stein** [comment]
That's exactly what I was looking at when I noticed my error, but thanks for your reply anyway!
