### ISSUE TITLE
Bad dependency LICENSEs

### ISSUE THREAD

**Issue by dcousens** [kach/nearley#396]
`nomnom` is unmaintained.
`npm` says LICENSE `none`,  but it does include an MIT license text.

It also uses `chalk@0.4.0` which has no LICENSE text,  but `npm` says MIT.

Any possibility to switch over to something without LICENSE woes?

I saw https://github.com/kach/nearley/pull/284,  which might be an easy switch.

**Comment by dcousens** [comment]
Related https://github.com/kach/nearley/issues/380

**Comment by msimerson** [comment]
`nonnom` dependency is gone, this can be closed.
