### ISSUE TITLE
. does not match '\u2028'

### ISSUE THREAD

**Issue by raine** [kach/nearley#400]
Not sure if intentional. If so, how can I match it?

```ne
start -> .
```

```js
const nearley = require('nearley')
const grammar = require('./test')

const parser = new nearley.Parser(
  nearley.Grammar.fromCompiled(grammar)
)

parser.feed('\u2028')
```

```
Error: invalid syntax at line 1 col 1:

   
  ^
Unexpected " "
```

**Comment by tjvr** [comment]
I'm not sure, but perhaps you want `[^]` rather than `.`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by raine** [comment]
Interesting. How does that work and why isn't it same as `.`?

**Comment by tjvr** [comment]
It's a quirk of JS RegExps. Quoting from the readme of a different project: 

> the dot /./ doesn't include newlines. Use [^] instead if you want to match newlines too.
> 
> Since an excluding character ranges like /[^ ]/ (which matches anything but a space) will include newlines, you have to be careful not to include them by accident!

The character class `[^]` matches anything. `^` in a character class means "anything but", so following it with an empty set just means "anything".

The dot `.` excludes newlines by default, unless you use the dotAll modifier, which Nearley doesn't. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by abitrolly** [comment]
@kach is there a place in docs to document dot `.` behavior and list things like `[^]`? I came to ask the same question - why `.` doesn't match newlines.
