### ISSUE TITLE
Parsing a string literal to check if it's Javascript compliant

### ISSUE THREAD

**Issue by diegoperini** [kach/nearley#402]
I tried `\"(\\.|[^"\\])*\"` and many other regex rules to parse string literals but no matter what I tried, I couldn't find a way to check if a string literal is Javascript compliant. Maybe my approach here is flawed. How do I check if a string literal starting and ending with `"`  have proper characters (all escaped properly) is a correct Js string?

Built-in string parser does not handle escape characters, hence the issue here.

**Comment by diegoperini** [comment]
I found [this](https://github.com/kach/nearley/blob/master/examples/json.ne#L45) useful enough. Thanks :)

**Comment by tjvr** [comment]
I have a regex somewhere that does this, and can dig it out if you would like 🙂 (spoiler: it's quite complicated!)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by diegoperini** [comment]
@tjvr I'd love it if you don't mind.

**Comment by tjvr** [comment]
I would try something like this:

```js
/"(?:\\["bfnrt\/\\]|\\u[a-fA-F0-9]{4}|[^"\\])*"/
```
