### ISSUE TITLE
Removing ambiguity

### ISSUE THREAD

**Issue by pfgithub** [kach/nearley#417]
I already see lots of issues with similar questions, but I still haven't figured out how to fix this.

I have a very simple grammar, it matches a list of words

```
words -> ( word _ ):*

word -> [A-Za-z]:+ {% d => d[0].join("") %}

_ -> [ \r\t,]:* {% d => null %}
```

However this allows arguments to parse in many ways. For an example input `first second` it could parse it like I want as `first` `second`, but it could also split it up into `fir` `st` `sec` `ond`. How do I get it so word matches as much as possible rather than splitting itself up.

**Comment by jtenner** [comment]
You should make the whitespace required.

**Comment by jtenner** [comment]
```ne
words -> _ word (__ word):* _ {% ([,first, last]) => {
  return [first, ...last.map(w => w[0][1])];
} %}
word -> [a-zA-Z]:+ {% d => d[0].join("") %}
_ -> [ \r\t\n,]:* {% d => null %}
__ -> [ \r\t\n,]:+  {% d => null %}
```

Your list is ambiguous because whitespace is optional. It successfully matches optional whitespace between words because the `+` operator isn't greedy like a regex.

**Comment by pfgithub** [comment]
that's annoying, I don't really want spaces to be required, and not having to work around a lexer is the reason I tried to use this.

Thanks.

**Comment by jtenner** [comment]
In order for your words to parse, you need required whitespace. Otherwise, how can you determine where the word starts and end?

**Comment by pfgithub** [comment]
What I mean is if in the future I also have strings, I want those strings to not require spaces.

Two words can only be seperated by spaces, but if I have a string like `word otherword"mystring"` I don't want to require a space between otherword and "mystring".

I'm just going to write my own parser for this because it's not a very common thing to want
