### ISSUE TITLE
Nearley memory leak?

### ISSUE THREAD

**Issue by vihanb** [kach/nearley#422]
So today I was parsing a not too large file (tried various files from 300ish lines to 2.5K lines) and had given nodejs 10GB of heap and within a minutes my app had used 10GB and proceeded to crash from lack of heap memory. I did some profiling and nearley seems to use a _very_ large about of memory to represent parser states:

<img width="538" alt="screen shot 2019-01-19 at 5 22 30 pm" src="https://user-images.githubusercontent.com/15314511/51434126-d169c300-1c0e-11e9-85f5-9f3dae4ba508.png">

Majority of the Arrays in the first row are also nearley States. Given that they are around 5 million (!!) State objects mereley 10s of seconds into parsing. Across the period these don't seem to be cleaned up. 

So my guess is that there is something in Nearley that persists the states somehow and as a result they aren't cleaned up. I've seen a few other issues regarding memory usage (#238) and speed— I don't mind slow parsing (given I have a relatively complex parser) but this out-of-control memory usage definitely appears to be a bug or at the very least undesirable behavior.

**Comment by tjvr** [comment]
It usually relates to how your grammar is constructed. Certain ways of writing grammars, particularly the built-in EBNF modifiers, can be very slow, and this is hard to fix because of how the algorithm works and how JS arrays work.

Using a tokenizer can help. If you can provide 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dmytro-shchurov** [comment]
I'd also like to get know why my xml attribute which contains image data about 3-100kB causes memory crash with using moo
```
const lexer = window.moo.compile({
        LBX: '<?xml',
        LCB: '</',
        LB: '<',
        RBX: '?>',
        RCB: '/>',
        RB: '>',
        EQ: '=',
        AMP: '&amp;',
        tagNameChar: /[a-zA-Z_][\w\:\.]*/,
        ws: {match: /\s+/, lineBreaks: true},
        attributeValue: {match: /"[^<&"]*"/, lineBreaks: true}
    });
...
tag -> %LB %tagNameChar tagAttributeList _ %RCB {% d => ({type: 'xml', name: d[0], xml: joiner(d)}) %}
tagAttributeList -> 
      null {% empter %} 
    | tagAttribute {% id %} 
    | tagAttributeList tagAttribute {% adder %}
tagAttribute -> __ %tagNameChar _ %EQ _ %attributeValue {% d => ` ${d[1]}=${d[5]}` %}
```
This is a part of my attempt to compose a working Razor syntax parser.
Thus, when %attributeValue has big size, browser crashes.
A previous attempt was without of using lexer, and had crashed as well.

**Comment by vihanb** [comment]
Oh FYI: just for future people seeing this bug. What I found in my case is there was a small ambiguity but it was on something small like whitespace. As a result there would be probably millions of potential parsings that nearley would attempt to generate all of. While I do think nearley should have some way to deal with this. If you do encounter runaway memory usage it's probably your grammar. I would `bisect` and check for regressions to try to identify where the ambiguity would be
