### ISSUE TITLE
Can't get the offset property of the Error while calling feed

### ISSUE THREAD

**Issue by lmgonzalves** [kach/nearley#424]
First of all, congrats and thanks for an awesome parser!

My issue is that I can't get the `offset` property of the `error` while calling `feed`, as described in the **Using a parser** page of the documentation:
https://nearley.js.org/docs/parser

Specifically, the following code snippet, from the **Catching errors** section:

```javascript
try {
    parser.feed("Cow goes% moo.");
} catch (err) {
    console.log("Error at character " + parseError.offset); // "Error at character 9"
}
```

Actually, this code will throw a `ReferenceError: parseError is not defined`, but replacing `parseError` with `err` will print `Error at character undefined`, and not the expected message.

So, `offset` is `undefined`, and not what documentation describes.
Can I get this info otherwise, or is it something that should be fixed?

**Comment by tjvr** [comment]
There's a typo in that code: it should read `err.offset`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lmgonzalves** [comment]
Yes, I know, but even fixing that, `err.offset` is `undefined`.
Is it working properly for you?

**Comment by tjvr** [comment]
Oops, sorry for not spotting that part!

Can you show us what `err` actually is? 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lmgonzalves** [comment]
Ok, I've prepared a Codepen with a minimal working demo to show the issue, and in the process I've figured out what is the problem :)
https://codepen.io/lmgonzalves/project/editor/XWGbvr

Here is the grammar I'm using:

```nearley
@{%
const lexer = moo.compile({
  number: /[0-9]/,
})
%}

@lexer lexer

numbers -> %number %number %number
```

And here is the `main.js` script:

```js
const parser = new nearley.Parser(nearley.Grammar.fromCompiled(grammar))

try {
  parser.feed('a')
} catch (error) {
  console.log('Error at character ' + error.offset)
}
```

So, the problem seems to be with `moo`, if we don't define a token to match "anything else".
And a solution seems to be to include a token at the end that matches "anything else", like:

```js
const lexer = moo.compile({
  number: /[0-9]/,
  anything: /./
})
```

I don't know if it is the intended behavior or a proper solution, so, please let me know your thoughts :)

**Comment by lmgonzalves** [comment]
Here is another thing I just notted testing.

If I use this lexer instead:

```nearley
const lexer = moo.compile({
  number: /[0-9]+/, // one or more characters
  anything: /./
})
```

And then test the "123a" expression with this code:

```js
try {
  parser.feed('123a')
} catch (error) {
  console.log('Error at character ' + error.offset)
  console.log(error)
}
```

I get:

```
Error at character 1
Error: "invalid syntax at line 1 col 4:

  123a
     ^
Unexpected anything token: "a"
"
```

As you can see, it is taking "123" as the first character, as it is a `number` token. But I think a token is not a character, and I actually needs the character info, or column from the Error message (col 4).

**Comment by tjvr** [comment]
Ah, I didn't realise you're using a lexer.

The `offset` is based on how many tokens Nearley has seen, so it's `1` in your last example because the error is with the second token.

As for the rest, I'm afraid I think this is just how Nearley works.

Moo supports fallback tokens, by the way, which could help with your use case. They're sadly not documented yet: https://github.com/no-context/moo/pull/98

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lmgonzalves** [comment]
So, there is no way to get the same info provided in the error message?
I mean `line` and `col`?

If not, I think I will **parse** the error message to get it :)

**Comment by tjvr** [comment]
`parser.lexer` might have this information?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lmgonzalves** [comment]
Yes, `parser.lexer.index` give the `col`, and `parser.lexer.line` gives the `line`.
Thanks!!!

**Comment by tjvr** [comment]
Glad to hear it! :)
