### ISSUE TITLE
Using Moo lexer in browser

### ISSUE THREAD

**Issue by frantic0** [kach/nearley#425]
Hi,

thank you for Nearley, it is a useful tool.

I was hoping to use Nearley to build a DSL grammar. My use case requires a universal build (node runtime + browser). I just prototyped a grammar with the Moo tokenizer, as suggested by the docs, and it works well in node. 

However, I set up the browser-based test fixture and I can't seem to be able to run it. I got this error in the console: 
`ReferenceError: require is not defined`

I took peek at the parser generated from the grammar, I found this line:
`const moo = require("moo"); // this 'require' creates a node dependency`

I suppose this makes the parser unsuitable for the browser environment? Documentation doesn't seem to provide much information about running Nearley on a browser environment except for using the <script> tags.

Am I missing anything?

Thanks,
F

**Comment by jtenner** [comment]
Yes. You should probably be bundling your parser with `"moo"` itself using a module bundler.

https://webpack.js.org is a really good one.

If you're making a small web app as an example, you can also use https://parceljs.org to bundle your software for the web.

An older but still viable alternative might also be http://browserify.org/.

Hope this helps.

**Comment by frantic0** [comment]
Thank you so much for the hint, @jtenner!

I just set webpack and it's working fine now!

Best,

FØ

**Comment by tjvr** [comment]
Glad to hear it!
