### ISSUE TITLE
Help! First time trying to use Nearley to parse ADEXP

### ISSUE THREAD

**Issue by james-gardner** [kach/nearley#452]
Hi,

Apologies in advance as I'm new to the wonderful world of parsing with Nearley. I've been tasked with parsing 'ADEXP' messages that look like this:

```
-TITLE IFPL -BEGIN ADDR -FAC LIIRZEZX -FAC CFMUTACT-FAC EDDAYGCD -FAC
LSASFPLS -FAC LSAZZQZX -FAC LSAZZQZG -FAC LIPPZQZX -FAC LIIRZPZM -FAC
LIPPZEZA -FAC EDDZYNYS -FAC LYZZEDXX -FAC EDDFYQYX -FAC EDGGZQZA -FAC
LYZZEEXX -FAC EDDAYGLZ -FAC EDDXYIYT -FAC LAAAZQZX -FAC LDZOZQZY -FAC
LDZOZQZX -FAC LDZOZQZQ -FAC EDUUZQZA -FAC LGMDZQZI -FAC LGGGZQZQ
```
All of the strings in this example are considered 'keywords' in accordance with the ADEXP specification but keywords beginning with a '-' are considered fields. 

It made sense to begin my approach by using a lexer:

```
@{%
  const moo = require('moo');

  const lexer = moo.compile({
    field: /-[a-zA-Z]+/,
    whitespace: { match: /\s+/, lineBreaks: true },
    keyword: /[a-zA-Z-]+/,
  });
%}
```

Then define some expressions that make use of this:

```
@lexer lexer

# 5.2.1. Generalize across all field types.
field -> basic_field | list_field

# 5.2.3. Basic field.
basic_field -> %field %whitespace %keyword %whitespace:?

# 5.2.4. List Field.
list_field -> %field %whitespace basic_field
```
But when I try and run my code I'm presented with the following error:

```
Error: invalid syntax at line 1 col 13:

  -TITLE IFPL -BEGIN
              ^
Unexpected field token: "-BEGIN"
```
Like I said I'm new to this and still grappling with the concepts. I'd appreciate any help though as to what I might be doing wrong. I understood that the lexer would tokenize my input and it appears to do so when I run it against moo.js alone. 

Any thoughts?

**Comment by kach** [comment]
In the top-level of your grammar, do you make sure to match something like `field:+` to get multiple fields? If not, it will match the first field (-TITLE IFPL) and then get confused because it doesn't expect anything further.

**Comment by james-gardner** [comment]
Thanks for replying so quickly. That's the nudge I needed I reckon - it's working now. Is what I've done an appropriate usage of a lexer?

**Comment by kach** [comment]
Yep, that's how lexers should be used!
