### ISSUE TITLE
SyntaxError in ES5 builds

### ISSUE THREAD

**Issue by henry-alakazhang** [kach/nearley#457]
Hi,

The latest version (2.17.0) includes some ES2015 syntax, which breaks ES5 builds. Specifically, I get this error in my build:

```
Error: SyntaxError: Unexpected token name «j», expected punc «;»
```

In #453, it looks like the cause is the `let` used in the for loop, but all the `const` usage is probably not ideal either.

This also means the `builds for ES5` test doesn't work as intended, since it's really `builds for the local version of node`. The tests don't pass on Node v5.12 due to `let`s in the test code, for example. It might be better to set up ESLint or something similar to check for ES5 compatibility.

**Comment by airportyh** [comment]
Oops! I didn't realize that we were supporting ES5 syntax. Will keep that in mind for future reference.
