### ISSUE TITLE
Still ES6 code in lib

### ISSUE THREAD

**Issue by mgroenhoff** [kach/nearley#460]
I noticed that commit https://github.com/kach/nearley/commit/17a29fce14cce3cb55e4c885521995abda0a6df3 removed ES6+ code and I saw two more.
https://github.com/kach/nearley/blob/17a29fce14cce3cb55e4c885521995abda0a6df3/lib/nearley.js#L347
and
https://github.com/kach/nearley/blob/17a29fce14cce3cb55e4c885521995abda0a6df3/lib/nearley.js#L356
This is not an issue for me personally but it might be for users that still have to support older browsers.

Cheers!

**Comment by kach** [comment]
If you open a PR converting the consts to vars then I can merge it.
