### ISSUE TITLE
Arguments to configure lexer at runtime?

### ISSUE THREAD

**Issue by nhnicwaller** [kach/nearley#467]
I am constructing an [ER7](https://caristix.com/help-center/v3/test/task/hl7-er7-encoding/) parser using Nearley with Moo as the lexer.

ER7 is the better-known encoding scheme for HL7v2 messages. One complicating factor with ER7 is that the message header can reconfigure the delimiters used for the rest of the message. So a message using the default delimiters might look like this:

```
MSH|^~\&|Field 1|p1^p2^p3^p4|
```

But `*` could be swapped in as the component delimiter, yielding a message like this.

```
MSH|*~\&|Field 1|p1*p2*p3*p4|
```

This is quite an annoyance, and in fact has been [asked about](https://github.com/kach/nearley/issues/236) in the issues for this repository once before. 

Classifying the delimiters is clearly a job for the lexer, and Moo handles this easily. I've written a lexer with Moo that provides Nearly with normalized Token names like `componentDivider`. It looks something like this...

```
export function compileLexer(delimiters): moo.Lexer {
  return moo.states({
    main: {
      fieldDivider: delimiters.fieldSeparator,
      repeatField: delimiters.repeatSeparator,
```

This works very well when I'm using Moo alone because I can pass in an object with all the delimiters used in the current message. However, I've run into a tough spot with Nearley because there doesn't seem to be any way to provide the lexer with information about the message. The frontmatter for my grammar looks like this.

```
@{%
const lexer = require('./moo').compileLexer();
%}
@lexer lexer
```

If there was a way for me to pass the entire message to `compileLexer()` at this stage, that would be enough for the lexer to self-configure with the appropriate delimiters. But as far as I know, the message isn't available in this scope. Or alternately, the ability to pass a custom object into `nearley.Grammar.fromCompiled()` could also help with configuring the lexer at runtime.

Is there some other approach you could recommend?

**Comment by nhnicwaller** [comment]
Oh, I just realized it's possible to patch the lexer at runtime. This works perfectly.

```
er7Grammar       = nearley.Grammar.fromCompiled(grammar);
er7Grammar.lexer = compileLexer(getDelimiters(true, er7Message));
parser           = new nearley.Parser(er7Grammar);
```

**Comment by tjvr** [comment]
Glad you sorted it!
