### ISSUE TITLE
Thank you for nearley

### ISSUE THREAD

**Issue by thers** [kach/nearley#468]
Just wanted to say thank you for this thing. I was on talk about lambda calculus by @lucasfcosta and it blew my mind so I've tried implementing small compiler for completely made up lang with the only purpose - to explore lambda calculus. I wasn't updating this project but might be it will help someone with this awesome project.

Lambdas parser: https://github.com/thers/lambdas

**Comment by kach** [comment]
Cool project — and thanks for the kind words! :-)
