### ISSUE TITLE
Passing variables to grammar for contectual postprocessing

### ISSUE THREAD

**Issue by ryanking1809** [kach/nearley#469]
I have a nearley grammar set up to produce a different value depending on the `context` in which it's parsed. I've got this working using `require()` but it's super complicated as I need to keep track of everything that is calling the parser and must make sure the grammar knows which is the correct context to reference. 
It would be significantly easier if I could just pass a `context` variable to the grammar. I can do this by editing the output of `nearleyc` like so:
```js
const parser = new nearley.Parser(nearley.Grammar.fromCompiled(grammar(context)))
```
```js
(function (context) {
    var grammar = {
        Lexer: undefined,
        ParserRules: [
             ...,
             {"name": "localVar", "symbols": [{"literal":"$"}, "string"], "postprocess": d => context[d[1]]},
             ...
        ]
      , ParserStart: "value"
    }
    if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
       module.exports = grammar;
    } else {
       window.grammar = grammar;
    }
});
```

However, every time I rerun `nearleyc` the modifications get overwritten. Is there a way to write the `grammar.ne` file so it can be passed a variable for contextual postprocessing?

**Comment by kach** [comment]
Can you import the context from another file via https://nearley.js.org/docs/grammar#additional-js ?

**Comment by ryanking1809** [comment]
Yes, that's what I'm currently doing. But it's not ideal as there are multiple contexts, and I need some way for the grammar to reference the correct one using an ID. So currently I pass this as part of the string that is parsed. For example.

```js
"{contextId} $firstName + $lastName"
```

Would set the context first then process the rest of the string.
```js
@{% const context = require('./context') %}
context -> "{" string "}"		{% d => setContextById(d[1]) %}
localVar -> "$" string 		{% d => context.getProp(d[1]) %}
addVars -> localVar _ "+" _ localVar         {% d => Operations.add(d[0], d[4]) %}
```

So I'm effectively passing the context through the string.

---
Maybe I can elaborate - hopefully it makes sense!

Say I had a `User` object with the string `"$firstName + $lastName"` which adds the first and last name of the user. So the following user models will have different results base on which `User` parses the string.

```js
User {
    id: user1,
    firstName: "Mary",
    lastName: "Jane",
    fullName: "$firstName + $lastName" // returns "MaryJane"
}
User {
    id: user2,
    firstName: "John",
    lastName: "Doe",
    fullName: "$firstName + $lastName" // returns "JohnDoe"
}
```
That's ok, because I can set a global `context` variable before each parse. Things get a little more complicated when objects start referencing other objects. So say I had a `Users` object with a property `allNames`.
```js
Users {
    id: users1
    deafultName: "RyanKing",
    allNames: "$defaultName + (user1.fullName + user2.fullName)" // returns "RyanKingMaryJaneJohnDoe" 
}
```

So the context will start parsing for `users1`, then need to parse `user1` & `user2` first, before switching back the `users1` context to complete parsing the string. And to get this working I just add / replace the context into the string but it's a little more cumbersome than it would be if I could just pass the javascript object without modifying the string.

```js
"{user1}$firstName + $lastName"
```
or
```js
"user1.firstName + user1.lastName"
```

But it sounds like this might be the only way to do things?

**Comment by kach** [comment]
I'd just update your build system / Makefile to automatically prepend/postpend the stuff you've been adding manually each time you re-compile the parser. That fixes your nearley-overwriting-it problem.

**Comment by ryanking1809** [comment]
Ok great, I'll see if I can figure out how to do that!

**Comment by ryanking1809** [comment]
If I forked nearley to add a args parameter, would you be interested in merging it in? Or do you think it's too obscure a use case?

I'm thinking a syntax like this
```
@args [context, otherArg, etc]
```
and modifying generate.js
```js
generate.js = generate._default = generate.javascript = function (parser, exportName) {
        // add args to grammar function
        output += "(function ("+parser.args+") {\n";
        ...
        // if there's args the function should be called with the args later
        // when passing the grammar to the parser
        output += "})" + (!parser.args ? "()" : "") + ";\n";

        return output;
    };
```

**Comment by kach** [comment]
No, I probably won't, sorry. I think this was suggested in the past (#63?) but I was unconvinced at the time and am still not really convinced that nearley needs this.

**Comment by ryanking1809** [comment]
Thanks, sorry I missed that thread. It seems I could work around it if I have the context postprocess the parser results, but if feels more efficient to just do it during the parsing steps.

I might maintain a fork for my own purposes - thanks for your help! 
I'm very excited to see what I can produce with Nearley.

**Comment by ryanking1809** [comment]
I'll leave this here in case anyone is looking for a solution in the future. It's a bit of a hacky find and replace function, but it does the job. Just dump the following in a `generate.js` file and run `node generate.js`

```js
var exec = require("child_process").exec;
var fs = require("fs");

var inputFile = "grammar.ne";
var outputFile = "grammar.js";
var args = ["context"];

// execute nearleyc to produce generated js file
// then update the generated file to acepts args
exec(`nearleyc ${inputFile} -o ${outputFile}`, function(err, stdout, stderr) {
	if (err) return console.error(err);
	fs.readFile(outputFile, "utf8", function(err, data) {
		if (err) return console.log(err);
		// replace initial function def to accept args
		// then ensure function isn't executed until later
		var result = data
			.replace(
				`(function () {`,
				`export default function (${args.join(",")}) {`
			)
			.replace(`})();`, `};`);
		fs.writeFile(outputFile, result, "utf8", function(err) {
			if (err) return console.error(err);
		});
	});
});
```
This makes the grammar file a function that needs to be called with the introduced arguments.
```js
new nearley.Parser(nearley.Grammar.fromCompiled(grammar(context)))
```

**Comment by marthoff** [comment]
Hi ryanking1809,

I had a similar problem, but found a much easier solution maybe this helps someone.

I passed a variable to the grammar object when using it like this:
`
grammar.lookup = (name) => {
return map[name];
}
`

Then I can use this in my postprocessors like that:
`
variable -> [A-Z]:+ {% d => grammar.lookup(d[0]) %}
`

No need to change the generated code or other hacks.

Hope this helps.

Cheers,
Martin

**Comment by ryanking1809** [comment]
@marthoff oh that's smarter! Thanks!

**Comment by ryanking1809** [comment]
I just tried @marthoff's solution and it works well provided you don't haven't any sub-parsing events. 
ie. If you're parsing a string, and during that process, you start processing another string with a new context, you will lose the old context of the parent parser. Something to watch out for!

**Comment by aureliendepeyrelongue** [comment]
Good job @marthoff, we can create a Factory + send variables through parameters and set these variables inside the grammar context to create a customised and powerful parser.

**Comment by christian-2** [comment]
Could somebody please provide a concrete, complete example where a post processor gains access to the path of a file that is parsed with nearley. I could not make this work so far base on @marthoff's suggestion.

**Comment by frankthelen** [comment]
I am wondering if there is an "official" solution for this by now. From my point of view, it's a general requirement.

Anyways... sSince I am compiling to **Typescript** (`@preprocessor typescript`), @marthoff's approach doesn't work because the generated Typescript `interface Grammar` doesn't allow to easily add a new property `lookup`. So, I am rather following @ryanking1809's idea of adding contextual curry to the grammar -- adjusted to Typescript.

This is what's generated:
```typescript
const grammar: Grammar = {
   ...
};
```

This is how I am tweaking it:
```typescript
const grammar = (lookup: (name: string) => string | boolean | number): Grammar => ({
   ...
});
```

If you like it more general, you could also hand in a `context` with whatever you need.

From my point of view, it should not be too difficult to add such `context` as an "official" feature somehow.

Maybe this helps.

**Comment by ryanking1809** [comment]
I have got around to trying it yet, but I might suggest looking into ohm for this use case. (https://github.com/ohmjs/ohm)

It look like you may be able to pass in context at runtime via something like `addOperation('eval', makeOps(context))`
https://nextjournal.com/dubroy/ohm-parsing-made-easy
