### ISSUE TITLE
/$\d+/ gets ignored by nearly-test

### ISSUE THREAD

**Issue by slifty** [kach/nearley#473]
I have a grammar + lexer definition as follows:

```
@{%
	const moo = require('moo')
	const lexer = moo.compile({
		wildcard: /\$\d+/,
	})
%}

@lexer lexer

clause -> %wildcard
```

When I test this grammar with the input of `$1` I get an empty result set:

<img width="955" alt="image" src="https://user-images.githubusercontent.com/208884/66599822-21f4c800-eb72-11e9-9a8f-011a59d54140.png">

When I escape the `$`, I see my expected result.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/208884/66599868-389b1f00-eb72-11e9-8144-ab76b1263586.png">

This appears to be an issue either with nearley or nearley-test, since removing moo from the equation and directly writing the grammar (`clause -> "$" [\d]:+`) has the same problem:

**Comment by slifty** [comment]
Apologies. This is a PBCAK bash failure (e.g. `echo "$1"` displays an empty string).

Closing and moving along, nothing to see here folks!

**Comment by tjvr** [comment]
No worries 😄
