### ISSUE TITLE
Nearleyc is not a command.

### ISSUE THREAD

**Issue by Mwexim** [kach/nearley#481]
When trying to execute the nearleyc command, I get this error.
```bash
$ nearleyc
nearleyc : The term 'nearleyc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ nearleyc
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (nearleyc:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
This is probably an error on my side, and I had one of the same type before, but couldn't remember how to fix it. I already searched on google but didn't find any solution.
I did install nearley both local (--save) and global (-g) like the page stated.

I'll try to find a solution, but any help is appreciated!

**Comment by CHarcoalToast** [comment]
Suddenly it worked. Really weird...
