### ISSUE TITLE
[Question] Is there a way to get Grammar from more than one file?

### ISSUE THREAD

**Issue by Mwexim** [kach/nearley#483]
I am making a sort of language where everybody can contribute to. Everybody can add syntaxes and compile them.
When I get all the files from one specific directory (grammar files), and put them in an array, it doesn't seem to work. I can only use grammar from one file.

Is it possible to input like an Array or something, so I can use several compiled grammar files?

Edit: I tried concatenating the strings, but doesn't seem to work.

**Comment by TheGrandmother** [comment]
Yes, there is a import feature.
[At the bottom of the docs](https://nearley.js.org/docs/grammar)

**Comment by CHarcoalToast** [comment]
Sorry for the late reaction. I mean from the javascript files. Like you compiled everything and then you loop all the files in a certain directory for example and smash all their grammar together into one big grammar construction.
