### ISSUE TITLE
Nearly memory expansion hangs app on simple grammar

### ISSUE THREAD

**Issue by turner** [kach/nearley#494]
I recently installed Nearley to write a simple data file parser. 

Here is a fragment of a typical file:
```
##format=sw1 name=A549 genome=hg38
chromosome	start	end	x	y	z
trace 0
chr18 50000 100000 121702 120524 120359
chr18 100000 150000 121381 121344 120706
chr18 150000 200000 121032 121740 121470
trace 1
chr18 50000 100000 121727 121616 120815
chr18 100000 150000 121786 120787 121192
chr18 150000 200000 121216 120548 121989
trace 2
chr18 50000 100000 121211 119760 120834
chr18 100000 150000 122007 120077 121333
chr18 150000 200000 122944 120197 121320

```

Here is the grammar:
https://github.com/igvteam/spacewalk/blob/spacewalk_grammar/grammar/grammar.ne

The generated parser works great for the above fragment. However it grinds to a halt and hangs the app when I feed it an actual file:
https://www.dropbox.com/s/ye435f8uw9cf1co/A549_chr21-28-30Mb.sw?dl=0

This is just a text file so it can be opened in Sublime or whatever.

Can someone suggest where to look for memory efficiencies in my grammar?

Thanks.

**Comment by turner** [comment]
So, a typical data file will have upwards of 50,000 records (rows of data).

**Comment by turner** [comment]
I tried simplifying the grammar to it's bare bones:

```
@{%
const acc = [];
%}

@builtin "number.ne"
@builtin "whitespace.ne"

file                    -> trace_rows           {% (d) => { return acc; } %}

trace_rows              -> trace_row            {% (d) => { acc.push(d[0]); } %}
                         | trace_rows trace_row {% (d) => { acc.push(d[1]); } %}

trace_row               -> "chr" int __ int __ int __ number_or_nan __ number_or_nan __ number_or_nan newline   {% (d) => { return { 'chr': d[1], 'start': d[3], 'end': d[5], 'x':d[7], 'y':d[9], 'z':d[11] } } %}

number_or_nan           -> decimal              {% id %}
                         | "nan"                {% id %}

newline                 -> [\r?\n|\r]           {% (d) => null %}

```
And it too fails on a 50,000 row data file. is Nearley not intended for ascii data files of this size?

**Comment by turner** [comment]
Is anyone available to respond to this issue? Is this project still being supported? Hello??

**Comment by turner** [comment]
I have added Moo as the lexer and performance is **far** worse.

With this grammar:

```
@{%
const moo = require("moo");

const lexer = moo.compile({
  ws:     /[ \t]+/,
  number: /[0-9]+/,
  identifier:  /[a-zA-Z0-9]+/,
  newline: {match: '\n', lineBreaks: true},
});
%}

@lexer lexer

file        -> trace_row:+      {% id %}

trace_row   -> %number %ws %number %ws %number %ws %number %ws %number %ws %number %newline
{% (d) => { return { chr:d[0], start:d[2], end:d[4], x:d[6], y:d[8], z:d[10] } } %}

```
Nearley chokes and grinds to a halt with just 20,000 rows of data:

Here is as snippet of the simplified dataset I created to test:

```
const str =
    '18 50000 100000 121702 120524 120359\n' +
    '18 100000 150000 121381 121344 120706\n' +
    '18 150000 200000 121032 121740 121470\n';

```

Is anyone out there seeing this?

**Comment by kach** [comment]
[discussed over email]
