### ISSUE TITLE
newline characters are parsed the same as newlines

### ISSUE THREAD

**Issue by andykais** [kach/nearley#523]
If I create a parser like so:

```nearley
InQuotes[X]               -> "'" $X "'"
StringTemplate            -> InQuotes[[^'\n\r]:*]
```

then both of these inputs are invalid with the error `Unexpected "\n".`:
```
'\n'
```
```
'
'
```

I would prefer that the latter is invalid but the former is valid (much how writing the former would be valid in say javascript, but the latter would not be. What I actually have to end up doing is writing
```
'\\n'
```
when I want to express a newline within quotes. Is there a way to make nearley parse strings closer to how most languages do?

**Comment by kach** [comment]
Hmm, it seems to work for me?

```
$ nearley-test <(pbpaste | nearleyc) -i "'\n'" -q
[
  [
    [ "'", [ [ '\\', 'n' ] ], "'" ]
  ]
]
```

If you're typing directly into nearley-test (as opposed to using -i) I wonder if hitting "enter" is creating a _second_ newline at the end of your input, which is what is causing the problem.

**Comment by andykais** [comment]
hmm Ill see if I can create a repro tonight, thanks for responding!

**Comment by andykais** [comment]
ah. Looks like my problem is that javascript string literals (`) interpret newline characters as newlines directly. So the following strings are equivilant:
```js
a = `\n`
b = `
`

a === b
// true
```
