### ISSUE TITLE
nearley-railroad feature request

### ISSUE THREAD

**Issue by Floffah** [kach/nearley#530]
I would like there to be a -r or --recursive option so it will follow any includes and variables used from them to show a more in depth documentation with sections and a contents bit at the top.

If there is a way to output nearley grammar to json without compiling it to a js file i could write a library to do this

**Comment by kach** [comment]
@Floffah You should be able to write this library! The JS that nearley compiles to is just a small module that I think exposes all the information you need. Even better, feel free to modify nearley-railroad directly and send a PR — I'll merge it and then your changes will be built in for all nearley users. Railroad is one of my favorite features but not really used as much as I wish… :)

**Comment by Floffah** [comment]
I might even make a way to use templates like JSDoc. This is so cool and I am writing a large language and would definitely need this. I will start writing this!

**Comment by Floffah** [comment]
Do you possibly have a Discord where i could ask you questions?

**Comment by kach** [comment]
Unfortunately, I don't currently have the bandwidth to give on-line support, and it's been long enough that I won't really be that good of a resource anyway. But railroad.js should be pretty clear and self-explanatory.

Also, please keep in mind that I am much likelier to merge a small focused set of changes to railroad.js than a large full-scale project, _especially_ one which introduces even more dependencies. That's not to discourage you from pursuing a large full-scale project (I'd be pleased to link to it from the documentation and all), but to help you decide ahead of time how you want to structure the project, depending on your goals.

**Comment by Floffah** [comment]
yea my library only introduces one new dependency (mustache, to generate a page based on a template) but i feel it would be easier to be its own library anyway because its turned into something that is a bit more complicated and not for someone who is just using it to test so no need to merge imo

**Comment by kach** [comment]
You may also be interested in #218 which I have personally been hoping someone will implement in a mergeable way!

**Comment by Floffah** [comment]
i would try and make a mergable version of this which i could maybe extend with that but i cant actually get the dependencies to install on windows or linux
