### ISSUE TITLE
Using forward slash as a keyword in Moo

### ISSUE THREAD

**Issue by jnbbender** [kach/nearley#546]
I am currently writing the following:

```
@{%
const moo.require("moo");

const lex = moo.compile({
   ws:          { match: /[ \t]+/, value: w => null }, 
   spd:         ['spd','speed'],
   spd_unit:  ['mps','m/s','mph'],
});
%}

@lexer lex

input -> %spd %ws %spd_unit
```
This is a very stripped down version.

When I do the following:
`nearley-test ./grammar.js --input "speed m/s"`  I get at syntax error at `speed m`
How do I handle a forward slash?  I tried escaping it and double-quoting but that did not work.

**Comment by Floffah** [comment]
i think that is talking about the whole m/s bit not just the /

**Comment by Floffah** [comment]
try changing `spd_unit:  ['mps','m/s','mph'],` to `spd_unit:  /m(\/s|ph|ps)/g`? if not im not sure

**Comment by jnbbender** [comment]
That one didn't work

**Comment by jnbbender** [comment]
Turns out I had another Moo rule that got in the way:
`alt_unit: ['meter','mtr','m','feet','ft']`
It was resolving to the %alt_unit rule.  Apologies for not posting a more complete example.
